# Generated by Django 2.2.6 on 2019-11-05 19:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
