# Generated by Django 2.2.6 on 2019-11-05 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_auto_20191105_2140'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='rating',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='date_posted',
            new_name='release_date',
        ),
    ]
